name: Push to Artifact Registry

on:
  push:
    branches:
    - master

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 363.0.0'
    - name: Use gcloud CLI
      run: gcloud info
    - name: Authorize
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
    - name: Build
      run: docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/msmsny/qkamura .
    - name: Push
      run: docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/msmsny/qkamura
